# 人脸识别系统

## 图片检测

In [ ]:
#导入cv2库
import cv2

#读取图片
img = cv2.imread('test.png')

#显示图片
cv2.imshow('image',img)

#等待显示
cv2.waitKey(0)
#释放内存
cv2.destroyAllWindows()

## 灰度转换

In [5]:
#导入cv2库
import cv2

#读取图片
img = cv2.imread('test.png')

#灰度转换
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#显示灰度
cv2.imshow('gray',gray_img)
#保存灰度图片
cv2.imwrite('gray.png',gray_img)

#显示图片
cv2.imshow('image',img)

#等待显示
cv2.waitKey(0)
#释放内存
cv2.destroyAllWindows()

## 修改尺寸

In [7]:
#导入cv2库
import cv2

#读取图片
img = cv2.imread('test.png')
#修改尺寸
resized_img = cv2.resize(img,(200,200))

#显示原图
cv2.imshow('image',img)
print('原图尺寸:',img.shape)
#显示修改后的图片
cv2.imshow('resized image',resized_img)
print('修改后尺寸:',resized_img.shape)

#等待
while True:
    if cv2.waitKey(0) == ord('q'):
        break

#释放内存
cv2.destroyAllWindows()

原图尺寸: (657, 460, 3)
修改后尺寸: (200, 200, 3)


## 绘制矩形

In [3]:
#导入cv2库
import cv2

#读取图片
img = cv2.imread('test.png')
#坐标
x, y, w, h = 100, 100, 200, 200
#绘制矩形
cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
#绘制圆形
cv2.circle(img, (x+w//2, y+h//2), 100, (0, 0, 255), 1)
#显示图片
cv2.imshow('image', img)
#等待
while True:
    if cv2.waitKey(0) == ord('q'):
        break

#释放内存
cv2.destroyAllWindows()

## 人脸检测

In [4]:
#导入cv2库
import cv2

#检测函数
def detect(img):
    #定义人脸识别分类器
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    #将图片灰度化
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #识别人脸
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    #返回识别结果
    return faces
    
#读取图片
img = cv2.imread('test.png')
#检测人脸
faces = detect(img)
#绘制矩形框
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
    #显示结果
    print('face detected')
#保存图片
cv2.imwrite('result.png', img)
#显示图片
cv2.imshow('image', img)
#等待
while True:
    if cv2.waitKey(0) == ord('q'):
        break

#释放内存
cv2.destroyAllWindows()

face detected


## 检测多个人脸

In [ ]:
#导入cv2库
import cv2

#检测函数
def detect(img):
    #定义人脸识别分类器
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    #将图片灰度化
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #识别人脸
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5)
    #返回识别结果
    return faces
    
#读取图片
img = cv2.imread('multi_face.png')
#检测人脸
faces = detect(img)
print('faces:', faces)
#绘制矩形框
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
#保存图片
cv2.imwrite('result.png', img)
#显示图片
cv2.imshow('image', img)
#等待
while True:
    if cv2.waitKey(0) == ord('q'):
        break

#释放内存
cv2.destroyAllWindows()

faces: [[1427  328   56   56]
 [ 919  249   53   53]
 [1136  300   63   63]
 [ 274  281   57   57]
 [ 770  189   54   54]
 [ 500  198   54   54]
 [ 771  252   56   56]
 [ 590  259   62   62]
 [1064  261   54   54]
 [ 134  265   54   54]
 [ 424  263   58   58]
 [ 418  160   51   51]
 [1027  305   55   55]
 [1223  263   64   64]
 [ 867  304   64   64]
 [1309  309   58   58]
 [1379  161   55   55]
 [ 502  312   61   61]
 [ 186  317   53   53]
 [1368  269   59   59]
 [ 673  314   70   70]
 [ 338  320   63   63]
 [ 901  162   50   50]
 [1237  164   47   47]
 [1323  110   50   50]
 [1000  169   53   53]
 [ 635  170   55   55]
 [ 304  124   50   50]]


In [ ]:
# 用dlib库进行人脸检测和特征提取
import dlib
import cv2

# 加载 Dlib 的人脸检测模型
detector = dlib.get_frontal_face_detector()

# 读取图像
img = cv2.imread('multi_face.png')
if img is None:
    raise ValueError("无法读取图像，请检查文件路径。")

# 将图像转换为灰度
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 检测人脸
faces = detector(gray)

# 绘制矩形框
for face in faces:
    x, y, w, h = (face.left(), face.top(), face.width(), face.height())
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
    print('face detected')

# 保存结果
cv2.imwrite('result.png', img)

# 显示图像
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

face detected
face detected


## 视频检测

In [ ]:
#导入cv2库
import cv2

#检测函数
def detect(img):
    #定义人脸识别分类器
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    #将图片灰度化
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #识别人脸
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5)
    #返回识别结果
    return faces
    
#读取摄像头
cap = cv2.VideoCapture(0)

#循环读取摄像头 
while (cap.isOpened()):
    #读取一帧
    ret, frame = cap.read()
    if ret == False:
        break
    #检测人脸
    faces = detect(frame)
    #绘制矩形框
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
    #显示图像
    cv2.imshow('frame', frame)
    #等待按键
    if cv2.waitKey(1) == ord('q'):
        break
    

#释放内存
cv2.destroyAllWindows()
#关闭摄像头

cap.release()

## 人脸录入

In [51]:
# 导入模块
import cv2

#检测函数
def detect(img):
    #定义人脸识别分类器
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    #将图片灰度化
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #识别人脸
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5)
    #返回识别结果
    return faces

# 摄像头
cap = cv2.VideoCapture(0)
num = 1

while (cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        # 调用检测函数
        faces = detect(frame)
        # 绘制矩形框
        # for (x, y, w, h) in faces:
        #     cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        # 显示图片
        cv2.imshow('frame', frame)
        # 按下s键保存图片
        if cv2.waitKey(1) & 0xFF == ord('s'):
            cv2.imwrite('./faces/test_'+str(num)+'.jpg', frame)
            num += 1
        # 按下q键退出
        elif cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

# 释放摄像头
cap.release()
# 关闭所有窗口
cv2.destroyAllWindows()

## 数据训练

In [49]:
import os
import cv2
import numpy as np
import PIL.Image

def getImagesAndLabels(path):
    # 获取图片路径
    imagePaths = [os.path.join(path,f) for f in os.listdir(path)]
    # 初始化样本列表和标签列表
    faceSamples=[]
    ids=[]
    #加载分类器
    face_dector = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    # 循环遍历图片路径列表
    for imagePath in imagePaths:
        # 打开图片
        PIL_img = PIL.Image.open(imagePath).convert('L')
        # 将图片转换为numpy数组
        img_numpy = np.array(PIL_img,'uint8')
        # 人脸检测
        faces = face_dector.detectMultiScale(img_numpy)
        # 获取图片ID
        id = int(os.path.split(imagePath)[-1].split(".")[0].split('_')[1])
        # 将图片和ID添加到样本列表和标签列表
        for (x,y,w,h) in faces:
            faceSamples.append(img_numpy[y:y+h,x:x+w])
        ids.append(id)
    # 转换为numpy数组
    ids = np.array(list(ids))
    print("图片数据:", faceSamples)
    print("图片id:", ids)
    return faceSamples,ids

# 定义人脸识别函数
def train_face_recognizer(faceSamples,ids):
    # 创建LBPH人脸识别器
    face_recognizer = cv2.face.LBPHFaceRecognizer_create()
    # 训练人脸识别器
    face_recognizer.train(faceSamples, ids)
    return face_recognizer

path = r'd:\MyWorkStation\pythonProjects\faceProject\faces'
# 获取图片路径和标签
faceSamples,ids = getImagesAndLabels(path)
# 训练人脸识别器
face_recognizer = train_face_recognizer(faceSamples,ids)
# 保存人脸识别器
face_recognizer.write('./trainer/face_recognizer.yml')

图片数据: [array([[148, 108,  27, ..., 133, 133, 131],
       [149, 115,  24, ..., 133, 132, 131],
       [147, 117,  26, ..., 133, 132, 131],
       ...,
       [ 20,  18,  19, ...,  26,  27,  27],
       [ 20,  19,  19, ...,  26,  27,  28],
       [ 21,  20,  19, ...,  27,  27,  28]], dtype=uint8), array([[52, 50, 48, ..., 35, 35, 35],
       [52, 50, 47, ..., 35, 36, 36],
       [50, 49, 46, ..., 34, 36, 36],
       ...,
       [49, 48, 46, ..., 67, 68, 58],
       [47, 45, 41, ..., 67, 61, 47],
       [37, 36, 34, ..., 66, 54, 38]], dtype=uint8), array([[ 94,  85,  72, ..., 104, 104, 104],
       [ 92,  82,  73, ..., 105, 106, 106],
       [ 85,  76,  70, ..., 104, 105, 106],
       ...,
       [138, 144, 145, ..., 128, 113, 109],
       [141, 145, 145, ..., 120, 113, 105],
       [147, 146, 145, ..., 126, 110, 107]], dtype=uint8), array([[ 53,  50,  47, ...,  43,  44,  46],
       [ 50,  47,  46, ...,  41,  42,  44],
       [ 46,  44,  45, ...,  40,  41,  43],
       ...,
       [132,

## 人脸识别

In [1]:
import cv2
import os
import urllib.request

# 加载训练好的模型
recogizer = cv2.face.LBPHFaceRecognizer_create()
recogizer.read('./trainer/face_recognizer.yml')
# 名称
names = ["yaojiaye","huge","zhoujielun"]

def face_detect(img):
    # 转换为灰度图
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # 加载人脸检测器
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    # 人脸检测
    faces = face_cascade.detectMultiScale(gray, 1.1, 5,cv2.CASCADE_SCALE_IMAGE, (100,100), (300,300))
    # 遍历检测到的人脸
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
        # 截取脸部图像
        roi_gray = gray[y:y+h, x:x+w]
        # 预测人脸
        id, conf = recogizer.predict(roi_gray)
        # 显示名称
        name = names[id-1]
        if conf < 50:
            cv2.putText(img, name, (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
            print(name)
        else:
            cv2.putText(img, 'unknown', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
            print('unknown')
    # 显示图片
    cv2.imshow('img', img)
    
cap = cv2.VideoCapture(0)

while (cap.isOpened()):
    ret, frame = cap.read()
    if ret == False:
        break
    face_detect(frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
        



unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
yaojiaye
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown